[pytest]
asyncio_mode = auto

filterwarnings =
    ignore::DeprecationWarning:fastapi.*:
    ignore::DeprecationWarning:app.main:
    ignore::sqlalchemy.exc.SAWarning
    ignore::pydantic.warnings.PydanticDeprecatedSince20
